version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: complaints
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://postgres:password@db:5432/complaints
      KAGGLE_CONFIG_DIR: /root/.kaggle

volumes:
  postgres_data:
